name: bloc_todos
description: feature layer --an todos app presentation UI and bloc
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  #packages
  #data layer
  local_storage:
    path: packages/local_storage
  todos_api:
    path: packages/todos_api
  #domain layer
  todos_repo:
    path: packages/todos_repo

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

  mockingjay: ^0.5.0

flutter:
  uses-material-design: true
  generate: true
