name: todos_api
description: data layer --api providing access to todos
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: any
  json_serializable: any
  json_annotation: ^4.8.1
  meta: any
  uuid: any

dev_dependencies:
  build_runner: any
  json_serializable: any
#  mocktail: ^1.0.3
  test: ^1.25.2
#  very_good_analysis: ^5.1.0
