name: local_storage
description: data layer --implements of the TodosApi
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  todos_api:
    path: ../todos_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
